

use std::str::FromStr;
use std::fmt;

use error::Error;


/// Country Code List: ISO 3166-1993 (E)
/// 
/// Download from: `https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes`
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum Country {
    AF,
    AX,
    AL,
    DZ,
    AS,
    AD,
    AO,
    AI,
    AQ,
    AG,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BJ,
    BM,
    BT,
    BO,
    BQ,
    BA,
    BW,
    BV,
    BR,
    IO,
    BN,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    CV,
    KY,
    CF,
    TD,
    CL,
    CN,
    CX,
    CC,
    CO,
    KM,
    CG,
    CD,
    CK,
    CR,
    CI,
    HR,
    CU,
    CW,
    CY,
    CZ,
    DK,
    DJ,
    DM,
    DO,
    EC,
    EG,
    SV,
    GQ,
    ER,
    EE,
    ET,
    FK,
    FO,
    FJ,
    FI,
    FR,
    GF,
    PF,
    TF,
    GA,
    GM,
    GE,
    DE,
    GH,
    GI,
    GR,
    GL,
    GD,
    GP,
    GU,
    GT,
    GG,
    GN,
    GW,
    GY,
    HT,
    HM,
    VA,
    HN,
    HK,
    HU,
    IS,
    IN,
    ID,
    IR,
    IQ,
    IE,
    IM,
    IL,
    IT,
    JM,
    JP,
    JE,
    JO,
    KZ,
    KE,
    KI,
    KP,
    KR,
    KW,
    KG,
    LA,
    LV,
    LB,
    LS,
    LR,
    LY,
    LI,
    LT,
    LU,
    MO,
    MK,
    MG,
    MW,
    MY,
    MV,
    ML,
    MT,
    MH,
    MQ,
    MR,
    MU,
    YT,
    MX,
    FM,
    MD,
    MC,
    MN,
    ME,
    MS,
    MA,
    MZ,
    MM,
    NA,
    NR,
    NP,
    NL,
    NC,
    NZ,
    NI,
    NE,
    NG,
    NU,
    NF,
    MP,
    NO,
    OM,
    PK,
    PW,
    PS,
    PA,
    PG,
    PY,
    PE,
    PH,
    PN,
    PL,
    PT,
    PR,
    QA,
    RE,
    RO,
    RU,
    RW,
    BL,
    SH,
    KN,
    LC,
    MF,
    PM,
    VC,
    WS,
    SM,
    ST,
    SA,
    SN,
    RS,
    SC,
    SL,
    SG,
    SX,
    SK,
    SI,
    SB,
    SO,
    ZA,
    GS,
    SS,
    ES,
    LK,
    SD,
    SR,
    SJ,
    SZ,
    SE,
    CH,
    SY,
    TW,
    TJ,
    TZ,
    TH,
    TL,
    TG,
    TK,
    TO,
    TT,
    TN,
    TR,
    TM,
    TC,
    TV,
    UG,
    UA,
    AE,
    GB,
    US,
    UM,
    UY,
    UZ,
    VU,
    VE,
    VN,
    VG,
    VI,
    WF,
    EH,
    YE,
    ZM,
    ZW,
    EU,
    ZZ,
}


impl Country {

    pub fn name(&self) -> &'static str {
        match *self {
            Country::AF => "Afghanistan",
            Country::AX => "Åland Islands",
            Country::AL => "Albania",
            Country::DZ => "Algeria",
            Country::AS => "American Samoa",
            Country::AD => "Andorra",
            Country::AO => "Angola",
            Country::AI => "Anguilla",
            Country::AQ => "Antarctica",
            Country::AG => "Antigua and Barbuda",
            Country::AR => "Argentina",
            Country::AM => "Armenia",
            Country::AW => "Aruba",
            Country::AU => "Australia",
            Country::AT => "Austria",
            Country::AZ => "Azerbaijan",
            Country::BS => "Bahamas",
            Country::BH => "Bahrain",
            Country::BD => "Bangladesh",
            Country::BB => "Barbados",
            Country::BY => "Belarus",
            Country::BE => "Belgium",
            Country::BZ => "Belize",
            Country::BJ => "Benin",
            Country::BM => "Bermuda",
            Country::BT => "Bhutan",
            Country::BO => "Bolivia (Plurinational State of)",
            Country::BQ => "Bonaire, Sint Eustatius and Saba",
            Country::BA => "Bosnia and Herzegovina",
            Country::BW => "Botswana",
            Country::BV => "Bouvet Island",
            Country::BR => "Brazil",
            Country::IO => "British Indian Ocean Territory",
            Country::BN => "Brunei Darussalam",
            Country::BG => "Bulgaria",
            Country::BF => "Burkina Faso",
            Country::BI => "Burundi",
            Country::KH => "Cambodia",
            Country::CM => "Cameroon",
            Country::CA => "Canada",
            Country::CV => "Cabo Verde",
            Country::KY => "Cayman Islands",
            Country::CF => "Central African Republic",
            Country::TD => "Chad",
            Country::CL => "Chile",
            Country::CN => "China",
            Country::CX => "Christmas Island",
            Country::CC => "Cocos (Keeling) Islands",
            Country::CO => "Colombia",
            Country::KM => "Comoros",
            Country::CG => "Congo",
            Country::CD => "Congo (Democratic Republic of the)",
            Country::CK => "Cook Islands",
            Country::CR => "Costa Rica",
            Country::CI => "Côte d'Ivoire",
            Country::HR => "Croatia",
            Country::CU => "Cuba",
            Country::CW => "Curaçao",
            Country::CY => "Cyprus",
            Country::CZ => "Czech Republic",
            Country::DK => "Denmark",
            Country::DJ => "Djibouti",
            Country::DM => "Dominica",
            Country::DO => "Dominican Republic",
            Country::EC => "Ecuador",
            Country::EG => "Egypt",
            Country::SV => "El Salvador",
            Country::GQ => "Equatorial Guinea",
            Country::ER => "Eritrea",
            Country::EE => "Estonia",
            Country::ET => "Ethiopia",
            Country::FK => "Falkland Islands (Malvinas)",
            Country::FO => "Faroe Islands",
            Country::FJ => "Fiji",
            Country::FI => "Finland",
            Country::FR => "France",
            Country::GF => "French Guiana",
            Country::PF => "French Polynesia",
            Country::TF => "French Southern Territories",
            Country::GA => "Gabon",
            Country::GM => "Gambia",
            Country::GE => "Georgia",
            Country::DE => "Germany",
            Country::GH => "Ghana",
            Country::GI => "Gibraltar",
            Country::GR => "Greece",
            Country::GL => "Greenland",
            Country::GD => "Grenada",
            Country::GP => "Guadeloupe",
            Country::GU => "Guam",
            Country::GT => "Guatemala",
            Country::GG => "Guernsey",
            Country::GN => "Guinea",
            Country::GW => "Guinea-Bissau",
            Country::GY => "Guyana",
            Country::HT => "Haiti",
            Country::HM => "Heard Island and McDonald Islands",
            Country::VA => "Holy See",
            Country::HN => "Honduras",
            Country::HK => "Hong Kong",
            Country::HU => "Hungary",
            Country::IS => "Iceland",
            Country::IN => "India",
            Country::ID => "Indonesia",
            Country::IR => "Iran (Islamic Republic of)",
            Country::IQ => "Iraq",
            Country::IE => "Ireland",
            Country::IM => "Isle of Man",
            Country::IL => "Israel",
            Country::IT => "Italy",
            Country::JM => "Jamaica",
            Country::JP => "Japan",
            Country::JE => "Jersey",
            Country::JO => "Jordan",
            Country::KZ => "Kazakhstan",
            Country::KE => "Kenya",
            Country::KI => "Kiribati",
            Country::KP => "Korea (Democratic People's Republic of)",
            Country::KR => "Korea (Republic of)",
            Country::KW => "Kuwait",
            Country::KG => "Kyrgyzstan",
            Country::LA => "Lao People's Democratic Republic",
            Country::LV => "Latvia",
            Country::LB => "Lebanon",
            Country::LS => "Lesotho",
            Country::LR => "Liberia",
            Country::LY => "Libya",
            Country::LI => "Liechtenstein",
            Country::LT => "Lithuania",
            Country::LU => "Luxembourg",
            Country::MO => "Macao",
            Country::MK => "Macedonia (the former Yugoslav Republic of)",
            Country::MG => "Madagascar",
            Country::MW => "Malawi",
            Country::MY => "Malaysia",
            Country::MV => "Maldives",
            Country::ML => "Mali",
            Country::MT => "Malta",
            Country::MH => "Marshall Islands",
            Country::MQ => "Martinique",
            Country::MR => "Mauritania",
            Country::MU => "Mauritius",
            Country::YT => "Mayotte",
            Country::MX => "Mexico",
            Country::FM => "Micronesia (Federated States of)",
            Country::MD => "Moldova (Republic of)",
            Country::MC => "Monaco",
            Country::MN => "Mongolia",
            Country::ME => "Montenegro",
            Country::MS => "Montserrat",
            Country::MA => "Morocco",
            Country::MZ => "Mozambique",
            Country::MM => "Myanmar",
            Country::NA => "Namibia",
            Country::NR => "Nauru",
            Country::NP => "Nepal",
            Country::NL => "Netherlands",
            Country::NC => "New Caledonia",
            Country::NZ => "New Zealand",
            Country::NI => "Nicaragua",
            Country::NE => "Niger",
            Country::NG => "Nigeria",
            Country::NU => "Niue",
            Country::NF => "Norfolk Island",
            Country::MP => "Northern Mariana Islands",
            Country::NO => "Norway",
            Country::OM => "Oman",
            Country::PK => "Pakistan",
            Country::PW => "Palau",
            Country::PS => "Palestine, State of",
            Country::PA => "Panama",
            Country::PG => "Papua New Guinea",
            Country::PY => "Paraguay",
            Country::PE => "Peru",
            Country::PH => "Philippines",
            Country::PN => "Pitcairn",
            Country::PL => "Poland",
            Country::PT => "Portugal",
            Country::PR => "Puerto Rico",
            Country::QA => "Qatar",
            Country::RE => "Réunion",
            Country::RO => "Romania",
            Country::RU => "Russian Federation",
            Country::RW => "Rwanda",
            Country::BL => "Saint Barthélemy",
            Country::SH => "Saint Helena, Ascension and Tristan da Cunha",
            Country::KN => "Saint Kitts and Nevis",
            Country::LC => "Saint Lucia",
            Country::MF => "Saint Martin (French part)",
            Country::PM => "Saint Pierre and Miquelon",
            Country::VC => "Saint Vincent and the Grenadines",
            Country::WS => "Samoa",
            Country::SM => "San Marino",
            Country::ST => "Sao Tome and Principe",
            Country::SA => "Saudi Arabia",
            Country::SN => "Senegal",
            Country::RS => "Serbia",
            Country::SC => "Seychelles",
            Country::SL => "Sierra Leone",
            Country::SG => "Singapore",
            Country::SX => "Sint Maarten (Dutch part)",
            Country::SK => "Slovakia",
            Country::SI => "Slovenia",
            Country::SB => "Solomon Islands",
            Country::SO => "Somalia",
            Country::ZA => "South Africa",
            Country::GS => "South Georgia and the South Sandwich Islands",
            Country::SS => "South Sudan",
            Country::ES => "Spain",
            Country::LK => "Sri Lanka",
            Country::SD => "Sudan",
            Country::SR => "Suriname",
            Country::SJ => "Svalbard and Jan Mayen",
            Country::SZ => "Swaziland",
            Country::SE => "Sweden",
            Country::CH => "Switzerland",
            Country::SY => "Syrian Arab Republic",
            Country::TW => "Taiwan, Province of China",
            Country::TJ => "Tajikistan",
            Country::TZ => "Tanzania, United Republic of",
            Country::TH => "Thailand",
            Country::TL => "Timor-Leste",
            Country::TG => "Togo",
            Country::TK => "Tokelau",
            Country::TO => "Tonga",
            Country::TT => "Trinidad and Tobago",
            Country::TN => "Tunisia",
            Country::TR => "Turkey",
            Country::TM => "Turkmenistan",
            Country::TC => "Turks and Caicos Islands",
            Country::TV => "Tuvalu",
            Country::UG => "Uganda",
            Country::UA => "Ukraine",
            Country::AE => "United Arab Emirates",
            Country::GB => "United Kingdom of Great Britain and Northern Ireland",
            Country::US => "United States of America",
            Country::UM => "United States Minor Outlying Islands",
            Country::UY => "Uruguay",
            Country::UZ => "Uzbekistan",
            Country::VU => "Vanuatu",
            Country::VE => "Venezuela (Bolivarian Republic of)",
            Country::VN => "Viet Nam",
            Country::VG => "Virgin Islands (British)",
            Country::VI => "Virgin Islands (U.S.)",
            Country::WF => "Wallis and Futuna",
            Country::EH => "Western Sahara",
            Country::YE => "Yemen",
            Country::ZM => "Zambia",
            Country::ZW => "Zimbabwe",
            Country::EU => "Europe",
            Country::ZZ => "Unknown or unspecified country",
        }
    }
}


impl FromStr for Country {
    type Err = Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AF" => Ok(Country::AF),
            "AX" => Ok(Country::AX),
            "AL" => Ok(Country::AL),
            "DZ" => Ok(Country::DZ),
            "AS" => Ok(Country::AS),
            "AD" => Ok(Country::AD),
            "AO" => Ok(Country::AO),
            "AI" => Ok(Country::AI),
            "AQ" => Ok(Country::AQ),
            "AG" => Ok(Country::AG),
            "AR" => Ok(Country::AR),
            "AM" => Ok(Country::AM),
            "AW" => Ok(Country::AW),
            "AU" => Ok(Country::AU),
            "AT" => Ok(Country::AT),
            "AZ" => Ok(Country::AZ),
            "BS" => Ok(Country::BS),
            "BH" => Ok(Country::BH),
            "BD" => Ok(Country::BD),
            "BB" => Ok(Country::BB),
            "BY" => Ok(Country::BY),
            "BE" => Ok(Country::BE),
            "BZ" => Ok(Country::BZ),
            "BJ" => Ok(Country::BJ),
            "BM" => Ok(Country::BM),
            "BT" => Ok(Country::BT),
            "BO" => Ok(Country::BO),
            "BQ" => Ok(Country::BQ),
            "BA" => Ok(Country::BA),
            "BW" => Ok(Country::BW),
            "BV" => Ok(Country::BV),
            "BR" => Ok(Country::BR),
            "IO" => Ok(Country::IO),
            "BN" => Ok(Country::BN),
            "BG" => Ok(Country::BG),
            "BF" => Ok(Country::BF),
            "BI" => Ok(Country::BI),
            "KH" => Ok(Country::KH),
            "CM" => Ok(Country::CM),
            "CA" => Ok(Country::CA),
            "CV" => Ok(Country::CV),
            "KY" => Ok(Country::KY),
            "CF" => Ok(Country::CF),
            "TD" => Ok(Country::TD),
            "CL" => Ok(Country::CL),
            "CN" => Ok(Country::CN),
            "CX" => Ok(Country::CX),
            "CC" => Ok(Country::CC),
            "CO" => Ok(Country::CO),
            "KM" => Ok(Country::KM),
            "CG" => Ok(Country::CG),
            "CD" => Ok(Country::CD),
            "CK" => Ok(Country::CK),
            "CR" => Ok(Country::CR),
            "CI" => Ok(Country::CI),
            "HR" => Ok(Country::HR),
            "CU" => Ok(Country::CU),
            "CW" => Ok(Country::CW),
            "CY" => Ok(Country::CY),
            "CZ" => Ok(Country::CZ),
            "DK" => Ok(Country::DK),
            "DJ" => Ok(Country::DJ),
            "DM" => Ok(Country::DM),
            "DO" => Ok(Country::DO),
            "EC" => Ok(Country::EC),
            "EG" => Ok(Country::EG),
            "SV" => Ok(Country::SV),
            "GQ" => Ok(Country::GQ),
            "ER" => Ok(Country::ER),
            "EE" => Ok(Country::EE),
            "ET" => Ok(Country::ET),
            "FK" => Ok(Country::FK),
            "FO" => Ok(Country::FO),
            "FJ" => Ok(Country::FJ),
            "FI" => Ok(Country::FI),
            "FR" => Ok(Country::FR),
            "GF" => Ok(Country::GF),
            "PF" => Ok(Country::PF),
            "TF" => Ok(Country::TF),
            "GA" => Ok(Country::GA),
            "GM" => Ok(Country::GM),
            "GE" => Ok(Country::GE),
            "DE" => Ok(Country::DE),
            "GH" => Ok(Country::GH),
            "GI" => Ok(Country::GI),
            "GR" => Ok(Country::GR),
            "GL" => Ok(Country::GL),
            "GD" => Ok(Country::GD),
            "GP" => Ok(Country::GP),
            "GU" => Ok(Country::GU),
            "GT" => Ok(Country::GT),
            "GG" => Ok(Country::GG),
            "GN" => Ok(Country::GN),
            "GW" => Ok(Country::GW),
            "GY" => Ok(Country::GY),
            "HT" => Ok(Country::HT),
            "HM" => Ok(Country::HM),
            "VA" => Ok(Country::VA),
            "HN" => Ok(Country::HN),
            "HK" => Ok(Country::HK),
            "HU" => Ok(Country::HU),
            "IS" => Ok(Country::IS),
            "IN" => Ok(Country::IN),
            "ID" => Ok(Country::ID),
            "IR" => Ok(Country::IR),
            "IQ" => Ok(Country::IQ),
            "IE" => Ok(Country::IE),
            "IM" => Ok(Country::IM),
            "IL" => Ok(Country::IL),
            "IT" => Ok(Country::IT),
            "JM" => Ok(Country::JM),
            "JP" => Ok(Country::JP),
            "JE" => Ok(Country::JE),
            "JO" => Ok(Country::JO),
            "KZ" => Ok(Country::KZ),
            "KE" => Ok(Country::KE),
            "KI" => Ok(Country::KI),
            "KP" => Ok(Country::KP),
            "KR" => Ok(Country::KR),
            "KW" => Ok(Country::KW),
            "KG" => Ok(Country::KG),
            "LA" => Ok(Country::LA),
            "LV" => Ok(Country::LV),
            "LB" => Ok(Country::LB),
            "LS" => Ok(Country::LS),
            "LR" => Ok(Country::LR),
            "LY" => Ok(Country::LY),
            "LI" => Ok(Country::LI),
            "LT" => Ok(Country::LT),
            "LU" => Ok(Country::LU),
            "MO" => Ok(Country::MO),
            "MK" => Ok(Country::MK),
            "MG" => Ok(Country::MG),
            "MW" => Ok(Country::MW),
            "MY" => Ok(Country::MY),
            "MV" => Ok(Country::MV),
            "ML" => Ok(Country::ML),
            "MT" => Ok(Country::MT),
            "MH" => Ok(Country::MH),
            "MQ" => Ok(Country::MQ),
            "MR" => Ok(Country::MR),
            "MU" => Ok(Country::MU),
            "YT" => Ok(Country::YT),
            "MX" => Ok(Country::MX),
            "FM" => Ok(Country::FM),
            "MD" => Ok(Country::MD),
            "MC" => Ok(Country::MC),
            "MN" => Ok(Country::MN),
            "ME" => Ok(Country::ME),
            "MS" => Ok(Country::MS),
            "MA" => Ok(Country::MA),
            "MZ" => Ok(Country::MZ),
            "MM" => Ok(Country::MM),
            "NA" => Ok(Country::NA),
            "NR" => Ok(Country::NR),
            "NP" => Ok(Country::NP),
            "NL" => Ok(Country::NL),
            "NC" => Ok(Country::NC),
            "NZ" => Ok(Country::NZ),
            "NI" => Ok(Country::NI),
            "NE" => Ok(Country::NE),
            "NG" => Ok(Country::NG),
            "NU" => Ok(Country::NU),
            "NF" => Ok(Country::NF),
            "MP" => Ok(Country::MP),
            "NO" => Ok(Country::NO),
            "OM" => Ok(Country::OM),
            "PK" => Ok(Country::PK),
            "PW" => Ok(Country::PW),
            "PS" => Ok(Country::PS),
            "PA" => Ok(Country::PA),
            "PG" => Ok(Country::PG),
            "PY" => Ok(Country::PY),
            "PE" => Ok(Country::PE),
            "PH" => Ok(Country::PH),
            "PN" => Ok(Country::PN),
            "PL" => Ok(Country::PL),
            "PT" => Ok(Country::PT),
            "PR" => Ok(Country::PR),
            "QA" => Ok(Country::QA),
            "RE" => Ok(Country::RE),
            "RO" => Ok(Country::RO),
            "RU" => Ok(Country::RU),
            "RW" => Ok(Country::RW),
            "BL" => Ok(Country::BL),
            "SH" => Ok(Country::SH),
            "KN" => Ok(Country::KN),
            "LC" => Ok(Country::LC),
            "MF" => Ok(Country::MF),
            "PM" => Ok(Country::PM),
            "VC" => Ok(Country::VC),
            "WS" => Ok(Country::WS),
            "SM" => Ok(Country::SM),
            "ST" => Ok(Country::ST),
            "SA" => Ok(Country::SA),
            "SN" => Ok(Country::SN),
            "RS" => Ok(Country::RS),
            "SC" => Ok(Country::SC),
            "SL" => Ok(Country::SL),
            "SG" => Ok(Country::SG),
            "SX" => Ok(Country::SX),
            "SK" => Ok(Country::SK),
            "SI" => Ok(Country::SI),
            "SB" => Ok(Country::SB),
            "SO" => Ok(Country::SO),
            "ZA" => Ok(Country::ZA),
            "GS" => Ok(Country::GS),
            "SS" => Ok(Country::SS),
            "ES" => Ok(Country::ES),
            "LK" => Ok(Country::LK),
            "SD" => Ok(Country::SD),
            "SR" => Ok(Country::SR),
            "SJ" => Ok(Country::SJ),
            "SZ" => Ok(Country::SZ),
            "SE" => Ok(Country::SE),
            "CH" => Ok(Country::CH),
            "SY" => Ok(Country::SY),
            "TW" => Ok(Country::TW),
            "TJ" => Ok(Country::TJ),
            "TZ" => Ok(Country::TZ),
            "TH" => Ok(Country::TH),
            "TL" => Ok(Country::TL),
            "TG" => Ok(Country::TG),
            "TK" => Ok(Country::TK),
            "TO" => Ok(Country::TO),
            "TT" => Ok(Country::TT),
            "TN" => Ok(Country::TN),
            "TR" => Ok(Country::TR),
            "TM" => Ok(Country::TM),
            "TC" => Ok(Country::TC),
            "TV" => Ok(Country::TV),
            "UG" => Ok(Country::UG),
            "UA" => Ok(Country::UA),
            "AE" => Ok(Country::AE),
            "GB" => Ok(Country::GB),
            "US" => Ok(Country::US),
            "UM" => Ok(Country::UM),
            "UY" => Ok(Country::UY),
            "UZ" => Ok(Country::UZ),
            "VU" => Ok(Country::VU),
            "VE" => Ok(Country::VE),
            "VN" => Ok(Country::VN),
            "VG" => Ok(Country::VG),
            "VI" => Ok(Country::VI),
            "WF" => Ok(Country::WF),
            "EH" => Ok(Country::EH),
            "YE" => Ok(Country::YE),
            "ZM" => Ok(Country::ZM),
            "ZW" => Ok(Country::ZW),
            "EU" => Ok(Country::EU),
            "ZZ" => Ok(Country::ZZ),
            e @ _ => Err(Error::ParseCountryError(format!("Unknow Country Code ({})", e)))
        }
    }
}


impl fmt::Display for Country {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Country::AF => write!(f, "AF"),
            Country::AX => write!(f, "AX"),
            Country::AL => write!(f, "AL"),
            Country::DZ => write!(f, "DZ"),
            Country::AS => write!(f, "AS"),
            Country::AD => write!(f, "AD"),
            Country::AO => write!(f, "AO"),
            Country::AI => write!(f, "AI"),
            Country::AQ => write!(f, "AQ"),
            Country::AG => write!(f, "AG"),
            Country::AR => write!(f, "AR"),
            Country::AM => write!(f, "AM"),
            Country::AW => write!(f, "AW"),
            Country::AU => write!(f, "AU"),
            Country::AT => write!(f, "AT"),
            Country::AZ => write!(f, "AZ"),
            Country::BS => write!(f, "BS"),
            Country::BH => write!(f, "BH"),
            Country::BD => write!(f, "BD"),
            Country::BB => write!(f, "BB"),
            Country::BY => write!(f, "BY"),
            Country::BE => write!(f, "BE"),
            Country::BZ => write!(f, "BZ"),
            Country::BJ => write!(f, "BJ"),
            Country::BM => write!(f, "BM"),
            Country::BT => write!(f, "BT"),
            Country::BO => write!(f, "BO"),
            Country::BQ => write!(f, "BQ"),
            Country::BA => write!(f, "BA"),
            Country::BW => write!(f, "BW"),
            Country::BV => write!(f, "BV"),
            Country::BR => write!(f, "BR"),
            Country::IO => write!(f, "IO"),
            Country::BN => write!(f, "BN"),
            Country::BG => write!(f, "BG"),
            Country::BF => write!(f, "BF"),
            Country::BI => write!(f, "BI"),
            Country::KH => write!(f, "KH"),
            Country::CM => write!(f, "CM"),
            Country::CA => write!(f, "CA"),
            Country::CV => write!(f, "CV"),
            Country::KY => write!(f, "KY"),
            Country::CF => write!(f, "CF"),
            Country::TD => write!(f, "TD"),
            Country::CL => write!(f, "CL"),
            Country::CN => write!(f, "CN"),
            Country::CX => write!(f, "CX"),
            Country::CC => write!(f, "CC"),
            Country::CO => write!(f, "CO"),
            Country::KM => write!(f, "KM"),
            Country::CG => write!(f, "CG"),
            Country::CD => write!(f, "CD"),
            Country::CK => write!(f, "CK"),
            Country::CR => write!(f, "CR"),
            Country::CI => write!(f, "CI"),
            Country::HR => write!(f, "HR"),
            Country::CU => write!(f, "CU"),
            Country::CW => write!(f, "CW"),
            Country::CY => write!(f, "CY"),
            Country::CZ => write!(f, "CZ"),
            Country::DK => write!(f, "DK"),
            Country::DJ => write!(f, "DJ"),
            Country::DM => write!(f, "DM"),
            Country::DO => write!(f, "DO"),
            Country::EC => write!(f, "EC"),
            Country::EG => write!(f, "EG"),
            Country::SV => write!(f, "SV"),
            Country::GQ => write!(f, "GQ"),
            Country::ER => write!(f, "ER"),
            Country::EE => write!(f, "EE"),
            Country::ET => write!(f, "ET"),
            Country::FK => write!(f, "FK"),
            Country::FO => write!(f, "FO"),
            Country::FJ => write!(f, "FJ"),
            Country::FI => write!(f, "FI"),
            Country::FR => write!(f, "FR"),
            Country::GF => write!(f, "GF"),
            Country::PF => write!(f, "PF"),
            Country::TF => write!(f, "TF"),
            Country::GA => write!(f, "GA"),
            Country::GM => write!(f, "GM"),
            Country::GE => write!(f, "GE"),
            Country::DE => write!(f, "DE"),
            Country::GH => write!(f, "GH"),
            Country::GI => write!(f, "GI"),
            Country::GR => write!(f, "GR"),
            Country::GL => write!(f, "GL"),
            Country::GD => write!(f, "GD"),
            Country::GP => write!(f, "GP"),
            Country::GU => write!(f, "GU"),
            Country::GT => write!(f, "GT"),
            Country::GG => write!(f, "GG"),
            Country::GN => write!(f, "GN"),
            Country::GW => write!(f, "GW"),
            Country::GY => write!(f, "GY"),
            Country::HT => write!(f, "HT"),
            Country::HM => write!(f, "HM"),
            Country::VA => write!(f, "VA"),
            Country::HN => write!(f, "HN"),
            Country::HK => write!(f, "HK"),
            Country::HU => write!(f, "HU"),
            Country::IS => write!(f, "IS"),
            Country::IN => write!(f, "IN"),
            Country::ID => write!(f, "ID"),
            Country::IR => write!(f, "IR"),
            Country::IQ => write!(f, "IQ"),
            Country::IE => write!(f, "IE"),
            Country::IM => write!(f, "IM"),
            Country::IL => write!(f, "IL"),
            Country::IT => write!(f, "IT"),
            Country::JM => write!(f, "JM"),
            Country::JP => write!(f, "JP"),
            Country::JE => write!(f, "JE"),
            Country::JO => write!(f, "JO"),
            Country::KZ => write!(f, "KZ"),
            Country::KE => write!(f, "KE"),
            Country::KI => write!(f, "KI"),
            Country::KP => write!(f, "KP"),
            Country::KR => write!(f, "KR"),
            Country::KW => write!(f, "KW"),
            Country::KG => write!(f, "KG"),
            Country::LA => write!(f, "LA"),
            Country::LV => write!(f, "LV"),
            Country::LB => write!(f, "LB"),
            Country::LS => write!(f, "LS"),
            Country::LR => write!(f, "LR"),
            Country::LY => write!(f, "LY"),
            Country::LI => write!(f, "LI"),
            Country::LT => write!(f, "LT"),
            Country::LU => write!(f, "LU"),
            Country::MO => write!(f, "MO"),
            Country::MK => write!(f, "MK"),
            Country::MG => write!(f, "MG"),
            Country::MW => write!(f, "MW"),
            Country::MY => write!(f, "MY"),
            Country::MV => write!(f, "MV"),
            Country::ML => write!(f, "ML"),
            Country::MT => write!(f, "MT"),
            Country::MH => write!(f, "MH"),
            Country::MQ => write!(f, "MQ"),
            Country::MR => write!(f, "MR"),
            Country::MU => write!(f, "MU"),
            Country::YT => write!(f, "YT"),
            Country::MX => write!(f, "MX"),
            Country::FM => write!(f, "FM"),
            Country::MD => write!(f, "MD"),
            Country::MC => write!(f, "MC"),
            Country::MN => write!(f, "MN"),
            Country::ME => write!(f, "ME"),
            Country::MS => write!(f, "MS"),
            Country::MA => write!(f, "MA"),
            Country::MZ => write!(f, "MZ"),
            Country::MM => write!(f, "MM"),
            Country::NA => write!(f, "NA"),
            Country::NR => write!(f, "NR"),
            Country::NP => write!(f, "NP"),
            Country::NL => write!(f, "NL"),
            Country::NC => write!(f, "NC"),
            Country::NZ => write!(f, "NZ"),
            Country::NI => write!(f, "NI"),
            Country::NE => write!(f, "NE"),
            Country::NG => write!(f, "NG"),
            Country::NU => write!(f, "NU"),
            Country::NF => write!(f, "NF"),
            Country::MP => write!(f, "MP"),
            Country::NO => write!(f, "NO"),
            Country::OM => write!(f, "OM"),
            Country::PK => write!(f, "PK"),
            Country::PW => write!(f, "PW"),
            Country::PS => write!(f, "PS"),
            Country::PA => write!(f, "PA"),
            Country::PG => write!(f, "PG"),
            Country::PY => write!(f, "PY"),
            Country::PE => write!(f, "PE"),
            Country::PH => write!(f, "PH"),
            Country::PN => write!(f, "PN"),
            Country::PL => write!(f, "PL"),
            Country::PT => write!(f, "PT"),
            Country::PR => write!(f, "PR"),
            Country::QA => write!(f, "QA"),
            Country::RE => write!(f, "RE"),
            Country::RO => write!(f, "RO"),
            Country::RU => write!(f, "RU"),
            Country::RW => write!(f, "RW"),
            Country::BL => write!(f, "BL"),
            Country::SH => write!(f, "SH"),
            Country::KN => write!(f, "KN"),
            Country::LC => write!(f, "LC"),
            Country::MF => write!(f, "MF"),
            Country::PM => write!(f, "PM"),
            Country::VC => write!(f, "VC"),
            Country::WS => write!(f, "WS"),
            Country::SM => write!(f, "SM"),
            Country::ST => write!(f, "ST"),
            Country::SA => write!(f, "SA"),
            Country::SN => write!(f, "SN"),
            Country::RS => write!(f, "RS"),
            Country::SC => write!(f, "SC"),
            Country::SL => write!(f, "SL"),
            Country::SG => write!(f, "SG"),
            Country::SX => write!(f, "SX"),
            Country::SK => write!(f, "SK"),
            Country::SI => write!(f, "SI"),
            Country::SB => write!(f, "SB"),
            Country::SO => write!(f, "SO"),
            Country::ZA => write!(f, "ZA"),
            Country::GS => write!(f, "GS"),
            Country::SS => write!(f, "SS"),
            Country::ES => write!(f, "ES"),
            Country::LK => write!(f, "LK"),
            Country::SD => write!(f, "SD"),
            Country::SR => write!(f, "SR"),
            Country::SJ => write!(f, "SJ"),
            Country::SZ => write!(f, "SZ"),
            Country::SE => write!(f, "SE"),
            Country::CH => write!(f, "CH"),
            Country::SY => write!(f, "SY"),
            Country::TW => write!(f, "TW"),
            Country::TJ => write!(f, "TJ"),
            Country::TZ => write!(f, "TZ"),
            Country::TH => write!(f, "TH"),
            Country::TL => write!(f, "TL"),
            Country::TG => write!(f, "TG"),
            Country::TK => write!(f, "TK"),
            Country::TO => write!(f, "TO"),
            Country::TT => write!(f, "TT"),
            Country::TN => write!(f, "TN"),
            Country::TR => write!(f, "TR"),
            Country::TM => write!(f, "TM"),
            Country::TC => write!(f, "TC"),
            Country::TV => write!(f, "TV"),
            Country::UG => write!(f, "UG"),
            Country::UA => write!(f, "UA"),
            Country::AE => write!(f, "AE"),
            Country::GB => write!(f, "GB"),
            Country::US => write!(f, "US"),
            Country::UM => write!(f, "UM"),
            Country::UY => write!(f, "UY"),
            Country::UZ => write!(f, "UZ"),
            Country::VU => write!(f, "VU"),
            Country::VE => write!(f, "VE"),
            Country::VN => write!(f, "VN"),
            Country::VG => write!(f, "VG"),
            Country::VI => write!(f, "VI"),
            Country::WF => write!(f, "WF"),
            Country::EH => write!(f, "EH"),
            Country::YE => write!(f, "YE"),
            Country::ZM => write!(f, "ZM"),
            Country::ZW => write!(f, "ZW"),
            Country::EU => write!(f, "EU"),
            Country::ZZ => write!(f, "ZZ"),
        }
    }
}

